name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: CI
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Commit lint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.ts
      - name: Check Formatting
        run: npm run ci:format
      - name: Check Code-quality
        run: npm run ci:lint
      - name: Tests
        run: npm run ci:test