name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: CI
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependecies
        run: npm ci
      - name: Commit lint
        uses: rsksmart/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.ts
      - name: Check Formatting
        run: npm run ci:format
      - name: Check Code-quality
        run: npm run ci:lint
      - name: Tests
        run: npm run ci:test